spring:
  application:
    name: axon-server-example
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
axon:
  axonserver:
    enabled: true
  serializer:
    general: jackson3
    events: jackson3
    messages: jackson3

#logging:
#  level:
#    org.axonframework.messaging: DEBUG
#    org.axonframework.commandhandling: DEBUG
