spring:
  application:
    name: axon-server-example
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
axon:
  axonserver:
    enabled: true

#logging:
#  level:
#    org.axonframework.messaging: DEBUG
#    org.axonframework.commandhandling: DEBUG
